### PR TITLE
[ANALYZER-3616]-Chart Labels show incorrect formatting when different rows have "Matching Values"

### PR DESCRIPTION
**Pull request by denisprotopopov**
- fixing

### CODE REVIEW

**Comment by mchen-len-son** [comment]
@pamval @dcleao @graimundo please take a look.
thanks.

**Comment by denisprotopopov** [comment]
@pamval @dcleao @graimundo please take a look.
thanks.

**Comment by denisprotopopov** [comment]
@pamval @dcleao @graimundo please take a look.
thanks.

**Comment by kolinus** [comment]
@pedrofvteixeira  could you please take a look.

**Pull request merged**
