### PR TITLE
[PPP-3514] Use of vulnerable components - jquery - multiple versions …

### PR DESCRIPTION
**Pull request by mchen-len-son**
…1.x prior to 1.12

- updated jquery version to 1.12.4

### CODE REVIEW

**Comment by pamval** [comment]
@dcleao I think jquery is only used for examples, right? If so, please merge the pull request

**Comment by dcleao** [comment]
@pamval it's used for the example html files and for the public site: `site/root/js/vendor/jquery-1.12.4.min.js`. I tried it out in both places and have experienced no problems. I think @miguelleite should have a saying on the site part.

**Comment by miguelleite** [comment]
@dcleao @pamval tested on my side as well, found no problems. One thing that needs to be changed is the jQuery version that is being requested from Google CDN to match the suggested version ([check here](https://github.com/webdetails/ccc/blob/master/site/root/ctools/ccc/index.html#L4)).

**Comment by mchen-len-son** [comment]
@miguelleite @dcleao 
Thanks, guys. Updated the PR.

**Pull request merged**
